### ISSUE TITLE
Proposed changes to syntax highlight on "Getting started"

### ISSUE THREAD

**Issue by Trippy3** [pola-rs/polars-book#203]
[user_guide/src/quickstart/intro.md](https://pola-rs.github.io/polars-book/user-guide/quickstart/intro.html#lazy-quick-start)

https://github.com/pola-rs/polars-book/blob/7490a9982073397025f1a5e589a20a077e1e5aba/user_guide/src/quickstart/intro.md?plain=1#L100-L107

I think it should be `toml` rather than `text`.
~~~md
```toml
 # Rust Cargo.toml dependencies 
  
 [dependencies] 
 polars = { version = "0.24.3", features = ["lazy"] } 
 reqwest =  { version = "0.11.12", features = ["blocking"] } 
 color-eyre = "0.6" 
```
~~~

```toml
 # Rust Cargo.toml dependencies 
  
 [dependencies] 
 polars = { version = "0.24.3", features = ["lazy"] } 
 reqwest =  { version = "0.11.12", features = ["blocking"] } 
 color-eyre = "0.6" 
```
